import fs from 'fs'
import { transform } from 'lightningcss'
import { name } from '../../package.json'
import { Logger } from './logger'

type InjectThemesConfig = {
    themes?: Array<string>
    dtsPath?: string
    input: string
}

const UNIWIND_CSS_COMMENT = `/* Auto genereated by uniwind - do not modify */`

export const injectThemes = ({
    themes = ['light', 'dark'],
    dtsPath = 'uniwind.d.ts',
    input,
}: InjectThemesConfig) => {
    const stringifiedThemes = `[${themes.map(theme => `'${theme}'`).join(', ')}]`

    // d.ts generation
    fs.writeFileSync(
        dtsPath,
        [
            `// NOTE: This file is generated by ${name} and it should not be edited manually.`,
            `/// <reference types="${name}/types" />`,
            '',
            `declare module '${name}' {`,
            `    export interface UniwindConfig {`,
            `        themes: readonly ${stringifiedThemes}`,
            `    }`,
            `}`,
            '',
            `export {}`,
            '',
        ].join('\n'),
    )

    // css generation
    const themesVariables = Object.fromEntries(themes.map(theme => [theme, new Set<string>()]))
    const css = fs.readFileSync(input, 'utf-8')
    transform({
        code: Buffer.from(css),
        filename: 'uniwind.css',
        visitor: {
            Rule: rule => {
                if (rule.type === 'unknown' && rule.value.name === 'variant') {
                    const [firstPrelude] = rule.value.prelude

                    if (
                        !firstPrelude
                        || firstPrelude.type !== 'token'
                        || firstPrelude.value.type !== 'ident'
                        || !themes.includes(firstPrelude.value.value)
                    ) {
                        return
                    }

                    const theme = firstPrelude.value.value

                    rule.value.block?.forEach(block => {
                        if (block.type === 'dashed-ident' && block.value.startsWith('--color-')) {
                            themesVariables[theme]?.add(block.value)
                        }
                    })
                }
            },
        },
    })

    // Check if all themes have the same variables
    let hasErrors = false as boolean
    const hasVariables = Object.values(themesVariables).some(variables => variables.size > 0)

    Object.values(themesVariables).forEach(variables => {
        Object.entries(themesVariables).forEach(([checkedTheme, checkedVariables]) => {
            variables.forEach(variable => {
                if (!checkedVariables.has(variable)) {
                    Logger.error(`Uniwind: Theme ${checkedTheme} is missing variable ${variable}`)
                    hasErrors = true
                }
            })
        })
    })

    if (hasErrors) {
        throw new Error('Uniwind: All themes must have the same variables')
    }

    const cssLines = css.split('\n')
    const [openingLine, closingLine] = cssLines
        .map((line, index) => ({ line, index }))
        .filter(({ line }) => line === UNIWIND_CSS_COMMENT)
    const openingLineIndex = openingLine?.index
    const closingLineIndex = closingLine?.index
    const variablesCSS = hasVariables
        ? [
            '',
            '@theme {',
            ...Array.from(Object.values(themesVariables).at(0) ?? []).map(variable => `    ${variable}: unset;`),
            '}',
        ]
        : []
    const uniwindCSS = [
        UNIWIND_CSS_COMMENT,
        '',
        ...themes.map(theme => `@custom-variant ${theme} (&:where(.${theme}, .${theme} *));`),
        ...variablesCSS,
        '',
        UNIWIND_CSS_COMMENT,
    ]

    if (openingLineIndex === undefined && closingLineIndex === undefined) {
        fs.writeFileSync(
            input,
            [
                ...cssLines,
                ...uniwindCSS,
            ].join('\n'),
        )
    }

    if (openingLineIndex !== undefined && closingLineIndex !== undefined) {
        fs.writeFileSync(
            input,
            [
                ...cssLines.slice(0, openingLineIndex),
                ...uniwindCSS,
                ...cssLines.slice(closingLineIndex + 1),
            ].join('\n'),
        )
    }

    // js generation
    return `globalThis.__uniwindThemes__ = ${stringifiedThemes};`
}
