import fs from 'fs'
import { name } from '../../package.json'
import { buildCSS } from '../css'

type InjectThemesConfig = {
    themes?: Array<string>
    dtsPath?: string
    input: string
}

export const injectThemes = ({
    themes = ['light', 'dark'],
    dtsPath = 'uniwind-types.d.ts',
    input,
}: InjectThemesConfig) => {
    const stringifiedThemes = `[${themes.map(theme => `'${theme}'`).join(', ')}]`

    // d.ts generation
    fs.writeFileSync(
        dtsPath,
        [
            `// NOTE: This file is generated by ${name} and it should not be edited manually.`,
            `/// <reference types="${name}/types" />`,
            '',
            `declare module '${name}' {`,
            `    export interface UniwindConfig {`,
            `        themes: readonly ${stringifiedThemes}`,
            `    }`,
            `}`,
            '',
            `export {}`,
            '',
        ].join('\n'),
    )
    buildCSS(themes, input)

    // js generation
    return `globalThis.__uniwindThemes__ = ${stringifiedThemes};`
}
